sudo: required
services:
 - docker

before_install:
 - docker build -t rahmane/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true rahmane/react-test npm test

after-success:
 - docker build -t rahmane/multi-client ./client
 - docker build -t rahmane/multi-nginx ./nginx
 - docker build -t rahmane/multi-server ./server
 - docker build -t rahmane/multi-worker ./worker
 #log on to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # take the images of our projects to docker hub
 - docker push rahmane/multi-client
 - docker push rahmane/multi-nginx
 - docker push rahmane/multi-server
 - docker push rahmane/multi-worker
